# Generated by Django 3.2.16 on 2023-10-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marathons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathons.marathon')),
            ],
        ),
    ]
