# Generated by Django 3.2.16 on 2023-10-05 09:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='marathon_posters', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('start_location', models.CharField(max_length=255)),
                ('date_and_time', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('file_attachment', models.FileField(upload_to='marathon_attachments', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathons.marathon')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MarathonDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathons.distance')),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathons.marathon')),
            ],
        ),
        migrations.AddField(
            model_name='marathon',
            name='distances',
            field=models.ManyToManyField(through='marathons.MarathonDistance', to='marathons.Distance'),
        ),
    ]
