# Generated by Django 3.2.16 on 2023-10-09 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathons', '0003_alter_marathon_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='file_attachment',
            field=models.FileField(upload_to='marathon_attachments', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg'])]),
        ),
    ]
